// src/FakeProducts1-20.js
export const FakeProducts = [
  {
    name: "A.S.I Suit",
    description: "Premium tailored A.S.I suit for formal occasions.",
    price: 120.99,
    season: "Spring",
    mainPic: "a-s-i-suit.jpg",
    pics: ["a-s-i-suit1.jpg", "a-s-i-suit2.jpg", "a-s-i-suit3.jpg"],
    tags: ["Suit", "Formal"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 15 },
      { size: "L", color: "Gray", quantity: 8 },
    ],
  },
  {
    name: "Adidas Blue Hoodie",
    description: "Comfortable Adidas hoodie for casual wear.",
    price: 59.99,
    season: "Autumn",
    mainPic: "adidas-hoodie.jpg",
    pics: ["adidas-hoodie1.jpg", "adidas-hoodie2.jpg", "adidas-hoodie3.jpg"],
    tags: ["Hoodie", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 20 },
      { size: "M", color: "Blue", quantity: 25 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Adidas Soccer Jersey",
    description: "Official Adidas soccer jersey.",
    price: 75.0,
    season: "Summer",
    mainPic: "adidas-jersey.jpg",
    pics: ["adidas-jersey1.jpg", "adidas-jersey2.jpg", "adidas-jersey3.jpg"],
    tags: ["Jersey", "Sport"],
    variants: [
      { size: "S", color: "Red", quantity: 12 },
      { size: "M", color: "Red", quantity: 18 },
      { size: "L", color: "Red", quantity: 10 },
    ],
  },
  {
    name: "Blue Check Shirt",
    description: "Stylish blue checkered shirt for casual outings.",
    price: 45.0,
    season: "Spring",
    mainPic: "blue-check-shirt.jpg",
    pics: [
      "blue-check-shirt1.jpg",
      "blue-check-shirt2.jpg",
      "blue-check-shirt3.jpg",
    ],
    tags: ["Shirt", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 20 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Black Dress",
    description: "Elegant black dress for special events.",
    price: 85.0,
    season: "Winter",
    mainPic: "black-dress.jpg",
    pics: ["black-dress1.jpg", "black-dress2.jpg", "black-dress3.jpg"],
    tags: ["Dress", "Elegant"],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Brown Jacket",
    description: "Classic brown jacket for cold seasons.",
    price: 99.99,
    season: "Autumn",
    mainPic: "brown-jacket.jpg",
    pics: ["brown-jacket1.jpg", "brown-jacket2.jpg", "brown-jacket3.jpg"],
    tags: ["Jacket", "Casual"],
    variants: [
      { size: "S", color: "Brown", quantity: 12 },
      { size: "M", color: "Brown", quantity: 15 },
      { size: "L", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Classic White Tee",
    description: "Everyday classic white t-shirt.",
    price: 25.0,
    season: "Summer",
    mainPic: "white-tee.jpg",
    pics: ["white-tee1.jpg", "white-tee2.jpg", "white-tee3.jpg"],
    tags: ["T-Shirt", "Casual"],
    variants: [
      { size: "S", color: "White", quantity: 25 },
      { size: "M", color: "White", quantity: 30 },
      { size: "L", color: "White", quantity: 20 },
    ],
  },
  {
    name: "Denim Jacket",
    description: "Blue denim jacket with comfortable fit.",
    price: 70.0,
    season: "Spring",
    mainPic: "denim-jacket.jpg",
    pics: ["denim-jacket1.jpg", "denim-jacket2.jpg", "denim-jacket3.jpg"],
    tags: ["Jacket", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light floral dress for hot summer days.",
    price: 65.0,
    season: "Summer",
    mainPic: "floral-dress.jpg",
    pics: ["floral-dress1.jpg", "floral-dress2.jpg", "floral-dress3.jpg"],
    tags: ["Dress", "Summer"],
    variants: [
      { size: "S", color: "Floral", quantity: 10 },
      { size: "M", color: "Floral", quantity: 12 },
      { size: "L", color: "Floral", quantity: 8 },
    ],
  },
  {
    name: "Green Hoodie",
    description: "Comfortable green hoodie for casual wear.",
    price: 55.0,
    season: "Autumn",
    mainPic: "green-hoodie.jpg",
    pics: ["green-hoodie1.jpg", "green-hoodie2.jpg", "green-hoodie3.jpg"],
    tags: ["Hoodie", "Casual"],
    variants: [
      { size: "S", color: "Green", quantity: 18 },
      { size: "M", color: "Green", quantity: 20 },
      { size: "L", color: "Green", quantity: 15 },
    ],
  },
  {
    name: "Grey Sweatpants",
    description: "Soft grey sweatpants for lounging or workouts.",
    price: 40.0,
    season: "Winter",
    mainPic: "grey-sweatpants.jpg",
    pics: [
      "grey-sweatpants1.jpg",
      "grey-sweatpants2.jpg",
      "grey-sweatpants3.jpg",
    ],
    tags: ["Sweatpants", "Casual"],
    variants: [
      { size: "S", color: "Grey", quantity: 12 },
      { size: "M", color: "Grey", quantity: 15 },
      { size: "L", color: "Grey", quantity: 10 },
    ],
  },
  {
    name: "Leather Boots",
    description: "Durable leather boots for outdoor use.",
    price: 120.0,
    season: "Winter",
    mainPic: "leather-boots.jpg",
    pics: ["leather-boots1.jpg", "leather-boots2.jpg", "leather-boots3.jpg"],
    tags: ["Boots", "Outdoor"],
    variants: [
      { size: "S", color: "Brown", quantity: 5 },
      { size: "M", color: "Brown", quantity: 8 },
      { size: "L", color: "Brown", quantity: 6 },
    ],
  },
  {
    name: "Navy Blazer",
    description: "Formal navy blazer for office or events.",
    price: 130.0,
    season: "Autumn",
    mainPic: "navy-blazer.jpg",
    pics: ["navy-blazer1.jpg", "navy-blazer2.jpg", "navy-blazer3.jpg"],
    tags: ["Blazer", "Formal"],
    variants: [
      { size: "S", color: "Navy", quantity: 8 },
      { size: "M", color: "Navy", quantity: 12 },
      { size: "L", color: "Navy", quantity: 7 },
    ],
  },
  {
    name: "Pink Summer Dress",
    description: "Cute pink dress for sunny days.",
    price: 60.0,
    season: "Summer",
    mainPic: "pink-dress.jpg",
    pics: ["pink-dress1.jpg", "pink-dress2.jpg", "pink-dress3.jpg"],
    tags: ["Dress", "Summer"],
    variants: [
      { size: "S", color: "Pink", quantity: 12 },
      { size: "M", color: "Pink", quantity: 14 },
      { size: "L", color: "Pink", quantity: 8 },
    ],
  },
  {
    name: "Polo Shirt",
    description: "Classic polo shirt for casual wear.",
    price: 35.0,
    season: "Spring",
    mainPic: "polo-shirt.jpg",
    pics: ["polo-shirt1.jpg", "polo-shirt2.jpg", "polo-shirt3.jpg"],
    tags: ["Shirt", "Casual"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Red High Heels",
    description: "Elegant red high heels for parties.",
    price: 75.0,
    season: "Autumn",
    mainPic: "red-heels.jpg",
    pics: ["red-heels1.jpg", "red-heels2.jpg", "red-heels3.jpg"],
    tags: ["Heels", "Formal"],
    variants: [
      { size: "S", color: "Red", quantity: 6 },
      { size: "M", color: "Red", quantity: 8 },
      { size: "L", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Casual striped shirt for everyday wear.",
    price: 30.0,
    season: "Spring",
    mainPic: "striped-shirt.jpg",
    pics: ["striped-shirt1.jpg", "striped-shirt2.jpg", "striped-shirt3.jpg"],
    tags: ["Shirt", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 18 },
      { size: "M", color: "Blue", quantity: 22 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for office or casual wear.",
    price: 65.0,
    season: "Autumn",
    mainPic: "suede-loafers.jpg",
    pics: ["suede-loafers1.jpg", "suede-loafers2.jpg", "suede-loafers3.jpg"],
    tags: ["Loafers", "Casual"],
    variants: [
      { size: "S", color: "Brown", quantity: 7 },
      { size: "M", color: "Brown", quantity: 10 },
      { size: "L", color: "Brown", quantity: 6 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Stylish trench coat for chilly weather.",
    price: 150.0,
    season: "Winter",
    mainPic: "trench-coat.jpg",
    pics: ["trench-coat1.jpg", "trench-coat2.jpg", "trench-coat3.jpg"],
    tags: ["Coat", "Formal"],
    variants: [
      { size: "S", color: "Beige", quantity: 5 },
      { size: "M", color: "Beige", quantity: 8 },
      { size: "L", color: "Beige", quantity: 6 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Classic white sneakers for everyday use.",
    price: 60.0,
    season: "Spring",
    mainPic: "white-sneakers.jpg",
    pics: ["white-sneakers1.jpg", "white-sneakers2.jpg", "white-sneakers3.jpg"],
    tags: ["Sneakers", "Casual"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter.",
    price: 25.0,
    season: "Winter",
    mainPic: "wool-scarf.jpg",
    pics: ["wool-scarf1.jpg", "wool-scarf2.jpg", "wool-scarf3.jpg"],
    tags: ["Scarf", "Winter"],
    variants: [{ size: "One Size", color: "Gray", quantity: 30 }],
  },

  {
    name: "Black Leather Jacket",
    description: "Sleek black leather jacket for a bold look.",
    price: 180.0,
    season: "Autumn",
    mainPic: "black-leather-jacket.jpg",
    pics: [
      "black-leather-jacket1.jpg",
      "black-leather-jacket2.jpg",
      "black-leather-jacket3.jpg",
    ],
    tags: ["Jacket", "Leather"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Denim Jeans",
    description: "Classic blue denim jeans with comfortable fit.",
    price: 55.0,
    season: "Spring",
    mainPic: "denim-jeans.jpg",
    pics: ["denim-jeans1.jpg", "denim-jeans2.jpg", "denim-jeans3.jpg"],
    tags: ["Jeans", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 18 },
      { size: "M", color: "Blue", quantity: 22 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Floral Summer Dress 2",
    description: "Bright floral dress for summer events.",
    price: 68.0,
    season: "Summer",
    mainPic: "floral-dress2.jpg",
    pics: ["floral-dress2-1.jpg", "floral-dress2-2.jpg", "floral-dress2-3.jpg"],
    tags: ["Dress", "Summer"],
    variants: [
      { size: "S", color: "Floral", quantity: 12 },
      { size: "M", color: "Floral", quantity: 14 },
      { size: "L", color: "Floral", quantity: 9 },
    ],
  },
  {
    name: "Casual Hoodie",
    description: "Comfortable hoodie for casual outings.",
    price: 50.0,
    season: "Autumn",
    mainPic: "casual-hoodie.jpg",
    pics: ["casual-hoodie1.jpg", "casual-hoodie2.jpg", "casual-hoodie3.jpg"],
    tags: ["Hoodie", "Casual"],
    variants: [
      { size: "S", color: "Gray", quantity: 15 },
      { size: "M", color: "Gray", quantity: 20 },
      { size: "L", color: "Gray", quantity: 12 },
    ],
  },
  {
    name: "Summer Sandals",
    description: "Light sandals perfect for summer.",
    price: 30.0,
    season: "Summer",
    mainPic: "summer-sandals.jpg",
    pics: ["summer-sandals1.jpg", "summer-sandals2.jpg", "summer-sandals3.jpg"],
    tags: ["Sandals", "Summer"],
    variants: [
      { size: "S", color: "Brown", quantity: 20 },
      { size: "M", color: "Brown", quantity: 25 },
      { size: "L", color: "Brown", quantity: 18 },
    ],
  },
  {
    name: "Patterned Shirt",
    description: "Shirt with unique patterns for casual wear.",
    price: 40.0,
    season: "Spring",
    mainPic: "patterned-shirt.jpg",
    pics: [
      "patterned-shirt1.jpg",
      "patterned-shirt2.jpg",
      "patterned-shirt3.jpg",
    ],
    tags: ["Shirt", "Casual"],
    variants: [
      { size: "S", color: "Mixed", quantity: 18 },
      { size: "M", color: "Mixed", quantity: 22 },
      { size: "L", color: "Mixed", quantity: 15 },
    ],
  },
  {
    name: "Winter Coat",
    description: "Warm coat for cold winter days.",
    price: 150.0,
    season: "Winter",
    mainPic: "winter-coat.jpg",
    pics: ["winter-coat1.jpg", "winter-coat2.jpg", "winter-coat3.jpg"],
    tags: ["Coat", "Winter"],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Denim Jacket 2",
    description: "Classic denim jacket with modern fit.",
    price: 75.0,
    season: "Spring",
    mainPic: "denim-jacket2.jpg",
    pics: ["denim-jacket2-1.jpg", "denim-jacket2-2.jpg", "denim-jacket2-3.jpg"],
    tags: ["Jacket", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Classic Tee",
    description: "Simple and classic t-shirt for everyday wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-tee.jpg",
    pics: ["classic-tee1.jpg", "classic-tee2.jpg", "classic-tee3.jpg"],
    tags: ["T-Shirt", "Casual"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Sun Dress",
    description: "Light sundress for summer outings.",
    price: 60.0,
    season: "Summer",
    mainPic: "sun-dress.jpg",
    pics: ["sun-dress1.jpg", "sun-dress2.jpg", "sun-dress3.jpg"],
    tags: ["Dress", "Summer"],
    variants: [
      { size: "S", color: "Yellow", quantity: 12 },
      { size: "M", color: "Yellow", quantity: 14 },
      { size: "L", color: "Yellow", quantity: 9 },
    ],
  },
  {
    name: "Sweater Lethal",
    description: "Cozy sweater for colder days.",
    price: 55.0,
    season: "Autumn",
    mainPic: "sweater-lethal.jpg",
    pics: ["sweater-lethal1.jpg", "sweater-lethal2.jpg", "sweater-lethal3.jpg"],
    tags: ["Sweater", "Casual"],
    variants: [
      { size: "S", color: "Gray", quantity: 15 },
      { size: "M", color: "Gray", quantity: 18 },
      { size: "L", color: "Gray", quantity: 12 },
    ],
  },
  {
    name: "Tees",
    description: "Comfortable casual tee for all occasions.",
    price: 20.0,
    season: "Summer",
    mainPic: "tees.jpg",
    pics: ["tees1.jpg", "tees2.jpg", "tees3.jpg"],
    tags: ["T-Shirt", "Casual"],
    variants: [
      { size: "S", color: "Blue", quantity: 20 },
      { size: "M", color: "Blue", quantity: 25 },
      { size: "L", color: "Blue", quantity: 18 },
    ],
  },
  {
    name: "Tees 2",
    description: "Another casual tee variant.",
    price: 22.0,
    season: "Summer",
    mainPic: "tees2.jpg",
    pics: ["tees2-1.jpg", "tees2-2.jpg", "tees2-3.jpg"],
    tags: ["T-Shirt", "Casual"],
    variants: [
      { size: "S", color: "Green", quantity: 18 },
      { size: "M", color: "Green", quantity: 22 },
      { size: "L", color: "Green", quantity: 15 },
    ],
  },
  {
    name: "Turtleneck Sweater",
    description: "Warm turtleneck for chilly seasons.",
    price: 50.0,
    season: "Winter",
    mainPic: "turtleneck-sweater.jpg",
    pics: [
      "turtleneck-sweater1.jpg",
      "turtleneck-sweater2.jpg",
      "turtleneck-sweater3.jpg",
    ],
    tags: ["Sweater", "Winter"],
    variants: [
      { size: "S", color: "Black", quantity: 12 },
      { size: "M", color: "Black", quantity: 15 },
      { size: "L", color: "Black", quantity: 10 },
    ],
  },
  {
    name: "Unique Dress",
    description: "One-of-a-kind dress for special occasions.",
    price: 120.0,
    season: "Summer",
    mainPic: "unique-dress.jpg",
    pics: ["unique-dress1.jpg", "unique-dress2.jpg", "unique-dress3.jpg"],
    tags: ["Dress", "Elegant"],
    variants: [
      { size: "S", color: "Red", quantity: 5 },
      { size: "M", color: "Red", quantity: 7 },
      { size: "L", color: "Red", quantity: 4 },
    ],
  },
  {
    name: "White Suit 2",
    description: "Elegant white suit for formal events.",
    price: 180.0,
    season: "Spring",
    mainPic: "white-suit2.jpg",
    pics: ["white-suit2-1.jpg", "white-suit2-2.jpg", "white-suit2-3.jpg"],
    tags: ["Suit", "Formal"],
    variants: [
      { size: "S", color: "White", quantity: 5 },
      { size: "M", color: "White", quantity: 6 },
      { size: "L", color: "White", quantity: 4 },
    ],
  },
  {
    name: "White Suit",
    description: "Classic white suit for weddings or events.",
    price: 175.0,
    season: "Spring",
    mainPic: "white-suit.jpg",
    pics: ["white-suit1.jpg", "white-suit2.jpg", "white-suit3.jpg"],
    tags: ["Suit", "Formal"],
    variants: [
      { size: "S", color: "White", quantity: 5 },
      { size: "M", color: "White", quantity: 6 },
      { size: "L", color: "White", quantity: 4 },
    ],
  },
  {
    name: "Winter Essentials",
    description: "Bundle of winter essentials for cold days.",
    price: 200.0,
    season: "Winter",
    mainPic: "winter-essentials.jpg",
    pics: [
      "winter-essentials1.jpg",
      "winter-essentials2.jpg",
      "winter-essentials3.jpg",
    ],
    tags: ["Winter", "Bundle"],
    variants: [{ size: "One Size", color: "Mixed", quantity: 50 }],
  },
  {
    name: "YUS Formality Dress",
    description: "Stylish formal dress from YUS collection.",
    price: 130.0,
    season: "Autumn",
    mainPic: "yus-formality-dress.jpg",
    pics: [
      "yus-formality-dress1.jpg",
      "yus-formality-dress2.jpg",
      "yus-formality-dress3.jpg",
    ],
    tags: ["Dress", "Formal"],
    variants: [
      { size: "S", color: "Blue", quantity: 6 },
      { size: "M", color: "Blue", quantity: 8 },
      { size: "L", color: "Blue", quantity: 5 },
    ],
  },

  {
    name: "Red High Heels",
    description: "Elegant red high heels for evening occasions.",
    price: 85.0,
    season: "Autumn",
    mainPic: "red-high-heels.jpg",
    pics: ["red-high-heels1.jpg", "red-high-heels2.jpg", "red-high-heels3.jpg"],
    variants: [
      { size: "36", color: "Red", quantity: 8 },
      { size: "37", color: "Red", quantity: 10 },
      { size: "38", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Classic striped shirt for casual and office wear.",
    price: 45.0,
    season: "Spring",
    mainPic: "striped-shirt.jpg",
    pics: ["striped-shirt1.jpg", "striped-shirt2.jpg", "striped-shirt3.jpg"],
    variants: [
      { size: "S", color: "White/Blue", quantity: 15 },
      { size: "M", color: "White/Blue", quantity: 20 },
      { size: "L", color: "White/Blue", quantity: 12 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for everyday style.",
    price: 70.0,
    season: "Autumn",
    mainPic: "suede-loafers.jpg",
    pics: ["suede-loafers1.jpg", "suede-loafers2.jpg", "suede-loafers3.jpg"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Stylish trench coat for a sophisticated look.",
    price: 150.0,
    season: "Autumn",
    mainPic: "trench-coat.jpg",
    pics: ["trench-coat1.jpg", "trench-coat2.jpg", "trench-coat3.jpg"],
    variants: [
      { size: "S", color: "Beige", quantity: 8 },
      { size: "M", color: "Beige", quantity: 10 },
      { size: "L", color: "Beige", quantity: 6 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Classic white sneakers for casual wear.",
    price: 60.0,
    season: "Summer",
    mainPic: "white-sneakers.jpg",
    pics: ["white-sneakers1.jpg", "white-sneakers2.jpg", "white-sneakers3.jpg"],
    variants: [
      { size: "39", color: "White", quantity: 20 },
      { size: "40", color: "White", quantity: 25 },
      { size: "41", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter protection.",
    price: 35.0,
    season: "Winter",
    mainPic: "wool-scarf.jpg",
    pics: ["wool-scarf1.jpg", "wool-scarf2.jpg", "wool-scarf3.jpg"],
    variants: [{ size: "One Size", color: "Gray", quantity: 50 }],
  },
  {
    name: "Black Dress",
    description: "Elegant black dress suitable for any event.",
    price: 120.0,
    season: "Autumn",
    mainPic: "black-dress.jpg",
    pics: ["black-dress1.jpg", "black-dress2.jpg", "black-dress3.jpg"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Brown Jacket",
    description: "Casual brown jacket for everyday wear.",
    price: 90.0,
    season: "Autumn",
    mainPic: "brown-jacket.jpg",
    pics: ["brown-jacket1.jpg", "brown-jacket2.jpg", "brown-jacket3.jpg"],
    variants: [
      { size: "S", color: "Brown", quantity: 10 },
      { size: "M", color: "Brown", quantity: 12 },
      { size: "L", color: "Brown", quantity: 8 },
    ],
  },
  {
    name: "Classic White Tee",
    description: "Simple white t-shirt for daily wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-white-tee.jpg",
    pics: [
      "classic-white-tee1.jpg",
      "classic-white-tee2.jpg",
      "classic-white-tee3.jpg",
    ],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Denim Jacket",
    description: "Versatile denim jacket for casual style.",
    price: 80.0,
    season: "Spring",
    mainPic: "denim-jacket.jpg",
    pics: ["denim-jacket1.jpg", "denim-jacket2.jpg", "denim-jacket3.jpg"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light and breezy floral dress for summer.",
    price: 65.0,
    season: "Summer",
    mainPic: "floral-summer-dress.jpg",
    pics: [
      "floral-summer-dress1.jpg",
      "floral-summer-dress2.jpg",
      "floral-summer-dress3.jpg",
    ],
    variants: [
      { size: "S", color: "Floral", quantity: 12 },
      { size: "M", color: "Floral", quantity: 14 },
      { size: "L", color: "Floral", quantity: 9 },
    ],
  },
  {
    name: "Green Hoodie",
    description: "Comfortable green hoodie for casual wear.",
    price: 50.0,
    season: "Spring",
    mainPic: "green-hoodie.jpg",
    pics: ["green-hoodie1.jpg", "green-hoodie2.jpg", "green-hoodie3.jpg"],
    variants: [
      { size: "S", color: "Green", quantity: 15 },
      { size: "M", color: "Green", quantity: 18 },
      { size: "L", color: "Green", quantity: 12 },
    ],
  },
  {
    name: "Grey Sweatpants",
    description: "Cozy grey sweatpants for lounging or workouts.",
    price: 40.0,
    season: "Winter",
    mainPic: "grey-sweatpants.jpg",
    pics: [
      "grey-sweatpants1.jpg",
      "grey-sweatpants2.jpg",
      "grey-sweatpants3.jpg",
    ],
    variants: [
      { size: "S", color: "Grey", quantity: 20 },
      { size: "M", color: "Grey", quantity: 25 },
      { size: "L", color: "Grey", quantity: 18 },
    ],
  },
  {
    name: "Leather Boots",
    description: "Durable leather boots for outdoor wear.",
    price: 120.0,
    season: "Winter",
    mainPic: "leather-boots.jpg",
    pics: ["leather-boots1.jpg", "leather-boots2.jpg", "leather-boots3.jpg"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Navy Blazer",
    description: "Classic navy blazer for formal occasions.",
    price: 140.0,
    season: "Autumn",
    mainPic: "navy-blazer.jpg",
    pics: ["navy-blazer1.jpg", "navy-blazer2.jpg", "navy-blazer3.jpg"],
    variants: [
      { size: "S", color: "Navy", quantity: 10 },
      { size: "M", color: "Navy", quantity: 12 },
      { size: "L", color: "Navy", quantity: 8 },
    ],
  },
  {
    name: "Pink Summer Dress",
    description: "Bright pink dress perfect for summer events.",
    price: 70.0,
    season: "Summer",
    mainPic: "pink-summer-dress.jpg",
    pics: [
      "pink-summer-dress1.jpg",
      "pink-summer-dress2.jpg",
      "pink-summer-dress3.jpg",
    ],
    variants: [
      { size: "S", color: "Pink", quantity: 12 },
      { size: "M", color: "Pink", quantity: 14 },
      { size: "L", color: "Pink", quantity: 9 },
    ],
  },
  {
    name: "Polo Shirt",
    description: "Classic polo shirt for casual and semi-formal looks.",
    price: 55.0,
    season: "Spring",
    mainPic: "polo-shirt.jpg",
    pics: ["polo-shirt1.jpg", "polo-shirt2.jpg", "polo-shirt3.jpg"],
    variants: [
      { size: "S", color: "White", quantity: 15 },
      { size: "M", color: "White", quantity: 18 },
      { size: "L", color: "White", quantity: 12 },
    ],
  },
  {
    name: "Red High Heels",
    description: "Elegant red high heels for evening occasions.",
    price: 85.0,
    season: "Autumn",
    mainPic: "red-high-heels.jpg",
    pics: ["red-high-heels1.jpg", "red-high-heels2.jpg", "red-high-heels3.jpg"],
    variants: [
      { size: "36", color: "Red", quantity: 8 },
      { size: "37", color: "Red", quantity: 10 },
      { size: "38", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Classic striped shirt for casual and office wear.",
    price: 45.0,
    season: "Spring",
    mainPic: "striped-shirt.jpg",
    pics: ["striped-shirt1.jpg", "striped-shirt2.jpg", "striped-shirt3.jpg"],
    variants: [
      { size: "S", color: "White/Blue", quantity: 15 },
      { size: "M", color: "White/Blue", quantity: 20 },
      { size: "L", color: "White/Blue", quantity: 12 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for everyday style.",
    price: 70.0,
    season: "Autumn",
    mainPic: "suede-loafers.jpg",
    pics: ["suede-loafers1.jpg", "suede-loafers2.jpg", "suede-loafers3.jpg"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Classic trench coat for rainy and cool days.",
    price: 150.0,
    season: "Autumn",
    mainPic: "trench-coat.jpg",
    pics: ["trench-coat1.jpg", "trench-coat2.jpg", "trench-coat3.jpg"],
    variants: [
      { size: "S", color: "Beige", quantity: 10 },
      { size: "M", color: "Beige", quantity: 12 },
      { size: "L", color: "Beige", quantity: 8 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Versatile white sneakers for casual and sports looks.",
    price: 65.0,
    season: "Spring",
    mainPic: "white-sneakers.jpg",
    pics: ["white-sneakers1.jpg", "white-sneakers2.jpg", "white-sneakers3.jpg"],
    variants: [
      { size: "40", color: "White", quantity: 15 },
      { size: "41", color: "White", quantity: 18 },
      { size: "42", color: "White", quantity: 12 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter wear.",
    price: 35.0,
    season: "Winter",
    mainPic: "wool-scarf.jpg",
    pics: ["wool-scarf1.jpg", "wool-scarf2.jpg", "wool-scarf3.jpg"],
    variants: [{ size: "One Size", color: "Grey", quantity: 20 }],
  },
  {
    name: "Black Leather Jacket",
    description: "Stylish black leather jacket for casual and night outs.",
    price: 200.0,
    season: "Winter",
    mainPic: "black-leather-jacket.jpg",
    pics: [
      "black-leather-jacket1.jpg",
      "black-leather-jacket2.jpg",
      "black-leather-jacket3.jpg",
    ],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Denim Jeans",
    description: "Classic blue denim jeans for everyday wear.",
    price: 55.0,
    season: "Spring",
    mainPic: "denim-jeans.jpg",
    pics: ["denim-jeans1.jpg", "denim-jeans2.jpg", "denim-jeans3.jpg"],
    variants: [
      { size: "S", color: "Blue", quantity: 12 },
      { size: "M", color: "Blue", quantity: 15 },
      { size: "L", color: "Blue", quantity: 10 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light floral dress for summer outings.",
    price: 60.0,
    season: "Summer",
    mainPic: "floral-summer-dress.jpg",
    pics: [
      "floral-summer-dress1.jpg",
      "floral-summer-dress2.jpg",
      "floral-summer-dress3.jpg",
    ],
    variants: [
      { size: "S", color: "Floral", quantity: 10 },
      { size: "M", color: "Floral", quantity: 12 },
      { size: "L", color: "Floral", quantity: 8 },
    ],
  },
  {
    name: "Casual Hoodie",
    description: "Comfortable hoodie for daily wear.",
    price: 45.0,
    season: "Winter",
    mainPic: "casual-hoodie.jpg",
    pics: ["casual-hoodie1.jpg", "casual-hoodie2.jpg", "casual-hoodie3.jpg"],
    variants: [
      { size: "S", color: "Grey", quantity: 12 },
      { size: "M", color: "Grey", quantity: 14 },
      { size: "L", color: "Grey", quantity: 10 },
    ],
  },
  {
    name: "Summer Sandals",
    description: "Light sandals for hot summer days.",
    price: 30.0,
    season: "Summer",
    mainPic: "summer-sandals.jpg",
    pics: ["summer-sandals1.jpg", "summer-sandals2.jpg", "summer-sandals3.jpg"],
    variants: [
      { size: "36", color: "Brown", quantity: 10 },
      { size: "37", color: "Brown", quantity: 12 },
      { size: "38", color: "Brown", quantity: 8 },
    ],
  },
  {
    name: "Patterned Shirt",
    description: "Shirt with unique patterns for casual style.",
    price: 50.0,
    season: "Spring",
    mainPic: "patterned-shirt.jpg",
    pics: [
      "patterned-shirt1.jpg",
      "patterned-shirt2.jpg",
      "patterned-shirt3.jpg",
    ],
    variants: [
      { size: "S", color: "Mixed", quantity: 12 },
      { size: "M", color: "Mixed", quantity: 15 },
      { size: "L", color: "Mixed", quantity: 10 },
    ],
  },
  {
    name: "Winter Coat",
    description: "Heavy coat to stay warm during cold winter days.",
    price: 180.0,
    season: "Winter",
    mainPic: "winter-coat.jpg",
    pics: ["winter-coat1.jpg", "winter-coat2.jpg", "winter-coat3.jpg"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Classic Tee",
    description: "Simple and classic t-shirt for everyday wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-tee.jpg",
    pics: ["classic-tee1.jpg", "classic-tee2.jpg", "classic-tee3.jpg"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Sun Dress",
    description: "Bright sundress perfect for sunny days.",
    price: 55.0,
    season: "Summer",
    mainPic: "sun-dress.jpg",
    pics: ["sun-dress1.jpg", "sun-dress2.jpg", "sun-dress3.jpg"],
    variants: [
      { size: "S", color: "Yellow", quantity: 12 },
      { size: "M", color: "Yellow", quantity: 14 },
      { size: "L", color: "Yellow", quantity: 10 },
    ],
  },
  {
    name: "Sweater Lethal",
    description: "Warm sweater with stylish design.",
    price: 60.0,
    season: "Winter",
    mainPic: "sweater-lethal.jpg",
    pics: ["sweater-lethal1.jpg", "sweater-lethal2.jpg", "sweater-lethal3.jpg"],
    variants: [
      { size: "S", color: "Grey", quantity: 10 },
      { size: "M", color: "Grey", quantity: 12 },
      { size: "L", color: "Grey", quantity: 8 },
    ],
  },
  {
    name: "Tees",
    description: "Casual tees for daily wear.",
    price: 20.0,
    season: "Summer",
    mainPic: "tees.jpg",
    pics: ["tees1.jpg", "tees2.jpg", "tees3.jpg"],
    variants: [
      { size: "S", color: "Black", quantity: 20 },
      { size: "M", color: "Black", quantity: 25 },
      { size: "L", color: "Black", quantity: 18 },
    ],
  },
  {
    name: "Turtleneck Sweater",
    description: "Stylish turtleneck sweater for winter.",
    price: 65.0,
    season: "Winter",
    mainPic: "turtleneck-sweater.jpg",
    pics: [
      "turtleneck-sweater1.jpg",
      "turtleneck-sweater2.jpg",
      "turtleneck-sweater3.jpg",
    ],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Unique Dress",
    description: "One-of-a-kind dress with unique patterns.",
    price: 80.0,
    season: "Autumn",
    mainPic: "unique-dress.jpg",
    pics: ["unique-dress1.jpg", "unique-dress2.jpg", "unique-dress3.jpg"],
    variants: [
      { size: "S", color: "Red", quantity: 8 },
      { size: "M", color: "Red", quantity: 10 },
      { size: "L", color: "Red", quantity: 6 },
    ],
  },
  {
    name: "White Suit",
    description: "Elegant white suit for formal events.",
    price: 190.0,
    season: "Spring",
    mainPic: "white-suit.jpg",
    pics: ["white-suit1.jpg", "white-suit2.jpg", "white-suit3.jpg"],
    variants: [
      { size: "S", color: "White", quantity: 6 },
      { size: "M", color: "White", quantity: 8 },
      { size: "L", color: "White", quantity: 5 },
    ],
  },
  {
    name: "Winter Essentials",
    description: "Collection of essential items for winter.",
    price: 150.0,
    season: "Winter",
    mainPic: "winter-essentials.jpg",
    pics: [
      "winter-essentials1.jpg",
      "winter-essentials2.jpg",
      "winter-essentials3.jpg",
    ],
    variants: [{ size: "One Size", color: "Mixed", quantity: 25 }],
  },
  {
    name: "YUS Formality Dress",
    description: "Formal dress for special occasions.",
    price: 120.0,
    season: "Autumn",
    mainPic: "yus-formality-dress.jpg",
    pics: [
      "yus-formality-dress1.jpg",
      "yus-formality-dress2.jpg",
      "yus-formality-dress3.jpg",
    ],
    variants: [
      { size: "S", color: "Blue", quantity: 6 },
      { size: "M", color: "Blue", quantity: 8 },
      { size: "L", color: "Blue", quantity: 5 },
    ],
  },
];
