// src/FakeProducts1-20.js
export const FakeProducts = [
  {
    name: "A.S.I Suit",
    description: "Premium tailored A.S.I suit for formal occasions.",
    price: 120.99,
    season: "Spring",
    mainPic: "a-s-i-suit.png",
    pics: ["a-s-i-suit1.png", "a-s-i-suit2.png", "a-s-i-suit3.png"],
    tags: ["Suit", "Formal", "Business", "Elegant", "Men's", "Tailored"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 15 },
      { size: "L", color: "Gray", quantity: 8 },
    ],
  },
  {
    name: "Adidas Blue Hoodie",
    description: "Comfortable Adidas hoodie for casual wear.",
    price: 59.99,
    season: "Autumn",
    mainPic: "adidas-hoodie.png",
    pics: ["adidas-hoodie1.png", "adidas-hoodie2.png", "adidas-hoodie3.png"],
    tags: ["Hoodie", "Casual", "Sportswear", "Comfort", "Streetwear", "Adidas"],
    variants: [
      { size: "S", color: "Blue", quantity: 20 },
      { size: "M", color: "Blue", quantity: 25 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Adidas Soccer Jersey",
    description: "Official Adidas soccer jersey.",
    price: 75.0,
    season: "Summer",
    mainPic: "adidas-jersey.png",
    pics: ["adidas-jersey1.png", "adidas-jersey2.png", "adidas-jersey3.png"],
    tags: ["Jersey", "Sport", "Athletic", "Soccer", "Adidas", "Teamwear"],
    variants: [
      { size: "S", color: "Red", quantity: 12 },
      { size: "M", color: "Red", quantity: 18 },
      { size: "L", color: "Red", quantity: 10 },
    ],
  },
  {
    name: "Blue Check Shirt",
    description: "Stylish blue checkered shirt for casual outings.",
    price: 45.0,
    season: "Spring",
    mainPic: "blue-check-shirt.png",
    pics: [
      "blue-check-shirt1.png",
      "blue-check-shirt2.png",
      "blue-check-shirt3.png",
    ],
    tags: ["Shirt", "Casual", "Checkered", "Button-up", "Men's", "Everyday"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 20 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Black Dress",
    description: "Elegant black dress for special events.",
    price: 85.0,
    season: "Winter",
    mainPic: "black-dress.png",
    pics: ["black-dress1.png", "black-dress2.png", "black-dress3.png"],
    tags: ["Dress", "Elegant", "Formal", "Evening Wear", "Women's", "Party"],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Brown Jacket",
    description: "Classic brown jacket for cold seasons.",
    price: 99.99,
    season: "Autumn",
    mainPic: "brown-jacket.png",
    pics: ["brown-jacket1.png", "brown-jacket2.png", "brown-jacket3.png"],
    tags: ["Jacket", "Casual", "Outerwear", "Men's", "Classic", "Warm"],
    variants: [
      { size: "S", color: "Brown", quantity: 12 },
      { size: "M", color: "Brown", quantity: 15 },
      { size: "L", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Classic White Tee",
    description: "Everyday classic white t-shirt.",
    price: 25.0,
    season: "Summer",
    mainPic: "white-tee.png",
    pics: ["white-tee1.png", "white-tee2.png", "white-tee3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "White", quantity: 25 },
      { size: "M", color: "White", quantity: 30 },
      { size: "L", color: "White", quantity: 20 },
    ],
  },
  {
    name: "Denim Jacket",
    description: "Blue denim jacket with comfortable fit.",
    price: 70.0,
    season: "Spring",
    mainPic: "denim-jacket.png",
    pics: ["denim-jacket1.png", "denim-jacket2.png", "denim-jacket3.png"],
    tags: ["Jacket", "Casual", "Denim", "Outerwear", "Unisex", "Classic"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light floral dress for hot summer days.",
    price: 65.0,
    season: "Summer",
    mainPic: "floral-dress.png",
    pics: ["floral-dress1.png", "floral-dress2.png", "floral-dress3.png"],
    tags: ["Dress", "Summer", "Floral", "Women's", "Lightweight", "Casual"],
    variants: [
      { size: "S", color: "Floral", quantity: 10 },
      { size: "M", color: "Floral", quantity: 12 },
      { size: "L", color: "Floral", quantity: 8 },
    ],
  },
  {
    name: "Green Hoodie",
    description: "Comfortable green hoodie for casual wear.",
    price: 55.0,
    season: "Autumn",
    mainPic: "green-hoodie.png",
    pics: ["green-hoodie1.png", "green-hoodie2.png", "green-hoodie3.png"],
    tags: ["Hoodie", "Casual", "Sportswear", "Comfort", "Streetwear", "Unisex"],
    variants: [
      { size: "S", color: "Green", quantity: 18 },
      { size: "M", color: "Green", quantity: 20 },
      { size: "L", color: "Green", quantity: 15 },
    ],
  },
  {
    name: "Grey Sweatpants",
    description: "Soft grey sweatpants for lounging or workouts.",
    price: 40.0,
    season: "Winter",
    mainPic: "grey-sweatpants.png",
    pics: [
      "grey-sweatpants1.png",
      "grey-sweatpants2.png",
      "grey-sweatpants3.png",
    ],
    tags: [
      "Sweatpants",
      "Casual",
      "Loungewear",
      "Athleisure",
      "Unisex",
      "Fleece",
    ],
    variants: [
      { size: "S", color: "Grey", quantity: 12 },
      { size: "M", color: "Grey", quantity: 15 },
      { size: "L", color: "Grey", quantity: 10 },
    ],
  },
  {
    name: "Leather Boots",
    description: "Durable leather boots for outdoor use.",
    price: 120.0,
    season: "Winter",
    mainPic: "leather-boots.png",
    pics: ["leather-boots1.png", "leather-boots2.png", "leather-boots3.png"],
    tags: ["Boots", "Outdoor", "Footwear", "Winter", "Durable", "Men's"],
    variants: [
      { size: "S", color: "Brown", quantity: 5 },
      { size: "M", color: "Brown", quantity: 8 },
      { size: "L", color: "Brown", quantity: 6 },
    ],
  },
  {
    name: "Navy Blazer",
    description: "Formal navy blazer for office or events.",
    price: 130.0,
    season: "Autumn",
    mainPic: "navy-blazer.png",
    pics: ["navy-blazer1.png", "navy-blazer2.png", "navy-blazer3.png"],
    tags: ["Blazer", "Formal", "Business", "Men's", "Classic", "Jacket"],
    variants: [
      { size: "S", color: "Navy", quantity: 8 },
      { size: "M", color: "Navy", quantity: 12 },
      { size: "L", color: "Navy", quantity: 7 },
    ],
  },
  {
    name: "Pink Summer Dress",
    description: "Cute pink dress for sunny days.",
    price: 60.0,
    season: "Summer",
    mainPic: "pink-dress.png",
    pics: ["pink-dress1.png", "pink-dress2.png", "pink-dress3.png"],
    tags: ["Dress", "Summer", "Casual", "Women's", "Lightweight", "Sundress"],
    variants: [
      { size: "S", color: "Pink", quantity: 12 },
      { size: "M", color: "Pink", quantity: 14 },
      { size: "L", color: "Pink", quantity: 8 },
    ],
  },
  {
    name: "Polo Shirt",
    description: "Classic polo shirt for casual wear.",
    price: 35.0,
    season: "Spring",
    mainPic: "polo-shirt.png",
    pics: ["polo-shirt1.png", "polo-shirt2.png", "polo-shirt3.png"],
    tags: ["Shirt", "Casual", "Polo", "Men's", "Classic", "Everyday"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Red High Heels",
    description: "Elegant red high heels for parties.",
    price: 75.0,
    season: "Autumn",
    mainPic: "red-heels.png",
    pics: ["red-heels1.png", "red-heels2.png", "red-heels3.png"],
    tags: ["Heels", "Formal", "Footwear", "Women's", "Party", "Elegant"],
    variants: [
      { size: "S", color: "Red", quantity: 6 },
      { size: "M", color: "Red", quantity: 8 },
      { size: "L", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Casual striped shirt for everyday wear.",
    price: 30.0,
    season: "Spring",
    mainPic: "striped-shirt.png",
    pics: ["striped-shirt1.png", "striped-shirt2.png", "striped-shirt3.png"],
    tags: ["Shirt", "Casual", "Striped", "Men's", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "Blue", quantity: 18 },
      { size: "M", color: "Blue", quantity: 22 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for office or casual wear.",
    price: 65.0,
    season: "Autumn",
    mainPic: "suede-loafers.png",
    pics: ["suede-loafers1.png", "suede-loafers2.png", "suede-loafers3.png"],
    tags: ["Loafers", "Casual", "Footwear", "Men's", "Comfort", "Office"],
    variants: [
      { size: "S", color: "Brown", quantity: 7 },
      { size: "M", color: "Brown", quantity: 10 },
      { size: "L", color: "Brown", quantity: 6 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Stylish trench coat for chilly weather.",
    price: 150.0,
    season: "Winter",
    mainPic: "trench-coat.png",
    pics: ["trench-coat1.png", "trench-coat2.png", "trench-coat3.png"],
    tags: ["Coat", "Formal", "Outerwear", "Women's", "Classic", "Business"],
    variants: [
      { size: "S", color: "Beige", quantity: 5 },
      { size: "M", color: "Beige", quantity: 8 },
      { size: "L", color: "Beige", quantity: 6 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Classic white sneakers for everyday use.",
    price: 60.0,
    season: "Spring",
    mainPic: "white-sneakers.png",
    pics: ["white-sneakers1.png", "white-sneakers2.png", "white-sneakers3.png"],
    tags: ["Sneakers", "Casual", "Footwear", "Unisex", "Classic", "Streetwear"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter.",
    price: 25.0,
    season: "Winter",
    mainPic: "wool-scarf.png",
    pics: ["wool-scarf1.png", "wool-scarf2.png", "wool-scarf3.png"],
    tags: ["Scarf", "Winter", "Accessory", "Unisex", "Warm", "Knit"],
    variants: [{ size: "One Size", color: "Gray", quantity: 30 }],
  },
  {
    name: "Black Leather Jacket",
    description: "Sleek black leather jacket for a bold look.",
    price: 180.0,
    season: "Autumn",
    mainPic: "black-leather-jacket.png",
    pics: [
      "black-leather-jacket1.png",
      "black-leather-jacket2.png",
      "black-leather-jacket3.png",
    ],
    tags: ["Jacket", "Leather", "Outerwear", "Men's", "Motorcycle", "Edgy"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Denim Jeans",
    description: "Classic blue denim jeans with comfortable fit.",
    price: 55.0,
    season: "Spring",
    mainPic: "denim-jeans.png",
    pics: ["denim-jeans1.png", "denim-jeans2.png", "denim-jeans3.png"],
    tags: ["Jeans", "Casual", "Denim", "Men's", "Everyday", "Classic"],
    variants: [
      { size: "S", color: "Blue", quantity: 18 },
      { size: "M", color: "Blue", quantity: 22 },
      { size: "L", color: "Blue", quantity: 15 },
    ],
  },
  {
    name: "Floral Summer Dress 2",
    description: "Bright floral dress for summer events.",
    price: 68.0,
    season: "Summer",
    mainPic: "floral-dress2.png",
    pics: ["floral-dress2-1.png", "floral-dress2-2.png", "floral-dress2-3.png"],
    tags: ["Dress", "Summer", "Floral", "Women's", "Party", "Casual"],
    variants: [
      { size: "S", color: "Floral", quantity: 12 },
      { size: "M", color: "Floral", quantity: 14 },
      { size: "L", color: "Floral", quantity: 9 },
    ],
  },
  ////////////////////////////////////////here1
  {
    name: "Casual Hoodie",
    description: "Comfortable hoodie for casual outings.",
    price: 50.0,
    season: "Autumn",
    mainPic: "casual-hoodie.png",
    pics: ["casual-hoodie1.png", "casual-hoodie2.png", "casual-hoodie3.png"],
    tags: ["Hoodie", "Casual", "Comfort", "Sportswear", "Unisex", "Fleece"],
    variants: [
      { size: "S", color: "Gray", quantity: 15 },
      { size: "M", color: "Gray", quantity: 20 },
      { size: "L", color: "Gray", quantity: 12 },
    ],
  },
  {
    name: "Summer Sandals",
    description: "Light sandals perfect for summer.",
    price: 30.0,
    season: "Summer",
    mainPic: "summer-sandals.png",
    pics: ["summer-sandals1.png", "summer-sandals2.png", "summer-sandals3.png"],
    tags: [
      "Sandals",
      "Summer",
      "Footwear",
      "Casual",
      "Lightweight",
      "Open-toe",
    ],
    variants: [
      { size: "S", color: "Brown", quantity: 20 },
      { size: "M", color: "Brown", quantity: 25 },
      { size: "L", color: "Brown", quantity: 18 },
    ],
  },
  {
    name: "Patterned Shirt",
    description: "Shirt with unique patterns for casual wear.",
    price: 40.0,
    season: "Spring",
    mainPic: "patterned-shirt.png",
    pics: [
      "patterned-shirt1.png",
      "patterned-shirt2.png",
      "patterned-shirt3.png",
    ],
    tags: ["Shirt", "Casual", "Patterned", "Men's", "Button-up", "Stylish"],
    variants: [
      { size: "S", color: "Mixed", quantity: 18 },
      { size: "M", color: "Mixed", quantity: 22 },
      { size: "L", color: "Mixed", quantity: 15 },
    ],
  },
  {
    name: "Winter Coat",
    description: "Warm coat for cold winter days.",
    price: 150.0,
    season: "Winter",
    mainPic: "winter-coat.png",
    pics: ["winter-coat1.png", "winter-coat2.png", "winter-coat3.png"],
    tags: ["Coat", "Winter", "Outerwear", "Warm", "Padded", "Unisex"],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Denim Jacket 2",
    description: "Classic denim jacket with modern fit.",
    price: 75.0,
    season: "Spring",
    mainPic: "denim-jacket2.png",
    pics: ["denim-jacket2-1.png", "denim-jacket2-2.png", "denim-jacket2-3.png"],
    tags: ["Jacket", "Casual", "Denim", "Outerwear", "Unisex", "Classic"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Classic Tee",
    description: "Simple and classic t-shirt for everyday wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-tee.png",
    pics: ["classic-tee1.png", "classic-tee2.png", "classic-tee3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Sun Dress",
    description: "Light sundress for summer outings.",
    price: 60.0,
    season: "Summer",
    mainPic: "sun-dress.png",
    pics: ["sun-dress1.png", "sun-dress2.png", "sun-dress3.png"],
    tags: ["Dress", "Summer", "Sundress", "Women's", "Casual", "Lightweight"],
    variants: [
      { size: "S", color: "Yellow", quantity: 12 },
      { size: "M", color: "Yellow", quantity: 14 },
      { size: "L", color: "Yellow", quantity: 9 },
    ],
  },
  {
    name: "Sweater Lethal",
    description: "Cozy sweater for colder days.",
    price: 55.0,
    season: "Autumn",
    mainPic: "sweater-lethal.png",
    pics: ["sweater-lethal1.png", "sweater-lethal2.png", "sweater-lethal3.png"],
    tags: ["Sweater", "Casual", "Cozy", "Knitwear", "Unisex", "Warm"],
    variants: [
      { size: "S", color: "Gray", quantity: 15 },
      { size: "M", color: "Gray", quantity: 18 },
      { size: "L", color: "Gray", quantity: 12 },
    ],
  },
  {
    name: "Tees",
    description: "Comfortable casual tee for all occasions.",
    price: 20.0,
    season: "Summer",
    mainPic: "tees.png",
    pics: ["tees1.png", "tees2.png", "tees3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "Blue", quantity: 20 },
      { size: "M", color: "Blue", quantity: 25 },
      { size: "L", color: "Blue", quantity: 18 },
    ],
  },
  {
    name: "Tees 2",
    description: "Another casual tee variant.",
    price: 22.0,
    season: "Summer",
    mainPic: "tees2.png",
    pics: ["tees2-1.png", "tees2-2.png", "tees2-3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "Green", quantity: 18 },
      { size: "M", color: "Green", quantity: 22 },
      { size: "L", color: "Green", quantity: 15 },
    ],
  },
  {
    name: "Turtleneck Sweater",
    description: "Warm turtleneck for chilly seasons.",
    price: 50.0,
    season: "Winter",
    mainPic: "turtleneck-sweater.png",
    pics: [
      "turtleneck-sweater1.png",
      "turtleneck-sweater2.png",
      "turtleneck-sweater3.png",
    ],
    tags: ["Sweater", "Winter", "Turtleneck", "Knitwear", "Cozy", "Unisex"],
    variants: [
      { size: "S", color: "Black", quantity: 12 },
      { size: "M", color: "Black", quantity: 15 },
      { size: "L", color: "Black", quantity: 10 },
    ],
  },
  {
    name: "Unique Dress",
    description: "One-of-a-kind dress for special occasions.",
    price: 120.0,
    season: "Summer",
    mainPic: "unique-dress.png",
    pics: ["unique-dress1.png", "unique-dress2.png", "unique-dress3.png"],
    tags: ["Dress", "Elegant", "Unique", "Formal", "Women's", "Party"],
    variants: [
      { size: "S", color: "Red", quantity: 5 },
      { size: "M", color: "Red", quantity: 7 },
      { size: "L", color: "Red", quantity: 4 },
    ],
  },
  {
    name: "White Suit 2",
    description: "Elegant white suit for formal events.",
    price: 180.0,
    season: "Spring",
    mainPic: "white-suit2.png",
    pics: ["white-suit2-1.png", "white-suit2-2.png", "white-suit2-3.png"],
    tags: ["Suit", "Formal", "Business", "Elegant", "Women's", "Wedding"],
    variants: [
      { size: "S", color: "White", quantity: 5 },
      { size: "M", color: "White", quantity: 6 },
      { size: "L", color: "White", quantity: 4 },
    ],
  },
  {
    name: "White Suit",
    description: "Classic white suit for weddings or events.",
    price: 175.0,
    season: "Spring",
    mainPic: "white-suit.png",
    pics: ["white-suit1.png", "white-suit2.png", "white-suit3.png"],
    tags: ["Suit", "Formal", "Business", "Elegant", "Men's", "Wedding"],
    variants: [
      { size: "S", color: "White", quantity: 5 },
      { size: "M", color: "White", quantity: 6 },
      { size: "L", color: "White", quantity: 4 },
    ],
  },
  {
    name: "Winter Essentials",
    description: "Bundle of winter essentials for cold days.",
    price: 200.0,
    season: "Winter",
    mainPic: "winter-essentials.png",
    pics: [
      "winter-essentials1.png",
      "winter-essentials2.png",
      "winter-essentials3.png",
    ],
    tags: ["Winter", "Bundle", "Essentials", "Set", "Unisex", "Gift"],
    variants: [{ size: "One Size", color: "Mixed", quantity: 50 }],
  },
  {
    name: "YUS Formality Dress",
    description: "Stylish formal dress from YUS collection.",
    price: 130.0,
    season: "Autumn",
    mainPic: "yus-formality-dress.png",
    pics: [
      "yus-formality-dress1.png",
      "yus-formality-dress2.png",
      "yus-formality-dress3.png",
    ],
    tags: ["Dress", "Formal", "Elegant", "Women's", "Evening Wear", "Designer"],
    variants: [
      { size: "S", color: "Blue", quantity: 6 },
      { size: "M", color: "Blue", quantity: 8 },
      { size: "L", color: "Blue", quantity: 5 },
    ],
  },
  {
    name: "Red High Heels",
    description: "Elegant red high heels for evening occasions.",
    price: 85.0,
    season: "Autumn",
    mainPic: "red-high-heels.png",
    pics: ["red-high-heels1.png", "red-high-heels2.png", "red-high-heels3.png"],
    tags: ["Heels", "Formal", "Footwear", "Women's", "Party", "Elegant"],
    variants: [
      { size: "36", color: "Red", quantity: 8 },
      { size: "37", color: "Red", quantity: 10 },
      { size: "38", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Classic striped shirt for casual and office wear.",
    price: 45.0,
    season: "Spring",
    mainPic: "striped-shirt.png",
    pics: ["striped-shirt1.png", "striped-shirt2.png", "striped-shirt3.png"],
    tags: ["Shirt", "Casual", "Striped", "Men's", "Button-up", "Office"],
    variants: [
      { size: "S", color: "White/Blue", quantity: 15 },
      { size: "M", color: "White/Blue", quantity: 20 },
      { size: "L", color: "White/Blue", quantity: 12 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for everyday style.",
    price: 70.0,
    season: "Autumn",
    mainPic: "suede-loafers.png",
    pics: ["suede-loafers1.png", "suede-loafers2.png", "suede-loafers3.png"],
    tags: ["Loafers", "Casual", "Footwear", "Men's", "Comfort", "Office"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Stylish trench coat for a sophisticated look.",
    price: 150.0,
    season: "Autumn",
    mainPic: "trench-coat.png",
    pics: ["trench-coat1.png", "trench-coat2.png", "trench-coat3.png"],
    tags: ["Coat", "Outerwear", "Trench", "Women's", "Classic", "Formal"],
    variants: [
      { size: "S", color: "Beige", quantity: 8 },
      { size: "M", color: "Beige", quantity: 10 },
      { size: "L", color: "Beige", quantity: 6 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Classic white sneakers for casual wear.",
    price: 60.0,
    season: "Summer",
    mainPic: "white-sneakers.png",
    pics: ["white-sneakers1.png", "white-sneakers2.png", "white-sneakers3.png"],
    tags: ["Sneakers", "Casual", "Footwear", "Unisex", "Classic", "Streetwear"],
    variants: [
      { size: "39", color: "White", quantity: 20 },
      { size: "40", color: "White", quantity: 25 },
      { size: "41", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter protection.",
    price: 35.0,
    season: "Winter",
    mainPic: "wool-scarf.png",
    pics: ["wool-scarf1.png", "wool-scarf2.png", "wool-scarf3.png"],
    tags: ["Scarf", "Winter", "Accessory", "Warm", "Unisex", "Knit"],
    variants: [{ size: "One Size", color: "Gray", quantity: 50 }],
  },
  {
    name: "Black Dress",
    description: "Elegant black dress suitable for any event.",
    price: 120.0,
    season: "Autumn",
    mainPic: "black-dress.png",
    pics: ["black-dress1.png", "black-dress2.png", "black-dress3.png"],
    tags: ["Dress", "Elegant", "Formal", "Evening Wear", "Women's", "Party"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Brown Jacket",
    description: "Casual brown jacket for everyday wear.",
    price: 90.0,
    season: "Autumn",
    mainPic: "brown-jacket.png",
    pics: ["brown-jacket1.png", "brown-jacket2.png", "brown-jacket3.png"],
    tags: ["Jacket", "Casual", "Outerwear", "Men's", "Everyday", "Autumn"],
    variants: [
      { size: "S", color: "Brown", quantity: 10 },
      { size: "M", color: "Brown", quantity: 12 },
      { size: "L", color: "Brown", quantity: 8 },
    ],
  },
  ///////////////here2
  {
    name: "Classic White Tee",
    description: "Simple white t-shirt for daily wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-white-tee.png",
    pics: [
      "classic-white-tee1.png",
      "classic-white-tee2.png",
      "classic-white-tee3.png",
    ],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Denim Jacket",
    description: "Versatile denim jacket for casual style.",
    price: 80.0,
    season: "Spring",
    mainPic: "denim-jacket.png",
    pics: ["denim-jacket1.png", "denim-jacket2.png", "denim-jacket3.png"],
    tags: ["Jacket", "Casual", "Denim", "Outerwear", "Unisex", "Classic"],
    variants: [
      { size: "S", color: "Blue", quantity: 15 },
      { size: "M", color: "Blue", quantity: 18 },
      { size: "L", color: "Blue", quantity: 12 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light and breezy floral dress for summer.",
    price: 65.0,
    season: "Summer",
    mainPic: "floral-summer-dress.png",
    pics: [
      "floral-summer-dress1.png",
      "floral-summer-dress2.png",
      "floral-summer-dress3.png",
    ],
    tags: ["Dress", "Summer", "Floral", "Women's", "Lightweight", "Casual"],
    variants: [
      { size: "S", color: "Floral", quantity: 12 },
      { size: "M", color: "Floral", quantity: 14 },
      { size: "L", color: "Floral", quantity: 9 },
    ],
  },
  {
    name: "Green Hoodie",
    description: "Comfortable green hoodie for casual wear.",
    price: 50.0,
    season: "Spring",
    mainPic: "green-hoodie.png",
    pics: ["green-hoodie1.png", "green-hoodie2.png", "green-hoodie3.png"],
    tags: ["Hoodie", "Casual", "Comfort", "Sportswear", "Unisex", "Fleece"],
    variants: [
      { size: "S", color: "Green", quantity: 15 },
      { size: "M", color: "Green", quantity: 18 },
      { size: "L", color: "Green", quantity: 12 },
    ],
  },
  {
    name: "Grey Sweatpants",
    description: "Cozy grey sweatpants for lounging or workouts.",
    price: 40.0,
    season: "Winter",
    mainPic: "grey-sweatpants.png",
    pics: [
      "grey-sweatpants1.png",
      "grey-sweatpants2.png",
      "grey-sweatpants3.png",
    ],
    tags: [
      "Sweatpants",
      "Casual",
      "Loungewear",
      "Athleisure",
      "Unisex",
      "Fleece",
    ],
    variants: [
      { size: "S", color: "Grey", quantity: 20 },
      { size: "M", color: "Grey", quantity: 25 },
      { size: "L", color: "Grey", quantity: 18 },
    ],
  },
  {
    name: "Leather Boots",
    description: "Durable leather boots for outdoor wear.",
    price: 120.0,
    season: "Winter",
    mainPic: "leather-boots.png",
    pics: ["leather-boots1.png", "leather-boots2.png", "leather-boots3.png"],
    tags: ["Boots", "Winter", "Footwear", "Durable", "Men's", "Outdoor"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Navy Blazer",
    description: "Classic navy blazer for formal occasions.",
    price: 140.0,
    season: "Autumn",
    mainPic: "navy-blazer.png",
    pics: ["navy-blazer1.png", "navy-blazer2.png", "navy-blazer3.png"],
    tags: ["Blazer", "Formal", "Business", "Men's", "Classic", "Jacket"],
    variants: [
      { size: "S", color: "Navy", quantity: 10 },
      { size: "M", color: "Navy", quantity: 12 },
      { size: "L", color: "Navy", quantity: 8 },
    ],
  },
  {
    name: "Pink Summer Dress",
    description: "Bright pink dress perfect for summer events.",
    price: 70.0,
    season: "Summer",
    mainPic: "pink-summer-dress.png",
    pics: [
      "pink-summer-dress1.png",
      "pink-summer-dress2.png",
      "pink-summer-dress3.png",
    ],
    tags: ["Dress", "Summer", "Casual", "Women's", "Lightweight", "Sundress"],
    variants: [
      { size: "S", color: "Pink", quantity: 12 },
      { size: "M", color: "Pink", quantity: 14 },
      { size: "L", color: "Pink", quantity: 9 },
    ],
  },
  {
    name: "Polo Shirt",
    description: "Classic polo shirt for casual and semi-formal looks.",
    price: 55.0,
    season: "Spring",
    mainPic: "polo-shirt.png",
    pics: ["polo-shirt1.png", "polo-shirt2.png", "polo-shirt3.png"],
    tags: ["Shirt", "Casual", "Polo", "Men's", "Classic", "Semi-Formal"],
    variants: [
      { size: "S", color: "White", quantity: 15 },
      { size: "M", color: "White", quantity: 18 },
      { size: "L", color: "White", quantity: 12 },
    ],
  },
  {
    name: "Red High Heels",
    description: "Elegant red high heels for evening occasions.",
    price: 85.0,
    season: "Autumn",
    mainPic: "red-high-heels.png",
    pics: ["red-high-heels1.png", "red-high-heels2.png", "red-high-heels3.png"],
    tags: ["Heels", "Formal", "Footwear", "Women's", "Party", "Elegant"],
    variants: [
      { size: "36", color: "Red", quantity: 8 },
      { size: "37", color: "Red", quantity: 10 },
      { size: "38", color: "Red", quantity: 5 },
    ],
  },
  {
    name: "Striped Shirt",
    description: "Classic striped shirt for casual and office wear.",
    price: 45.0,
    season: "Spring",
    mainPic: "striped-shirt.png",
    pics: ["striped-shirt1.png", "striped-shirt2.png", "striped-shirt3.png"],
    tags: ["Shirt", "Casual", "Striped", "Men's", "Button-up", "Office"],
    variants: [
      { size: "S", color: "White/Blue", quantity: 15 },
      { size: "M", color: "White/Blue", quantity: 20 },
      { size: "L", color: "White/Blue", quantity: 12 },
    ],
  },
  {
    name: "Suede Loafers",
    description: "Comfortable suede loafers for everyday style.",
    price: 70.0,
    season: "Autumn",
    mainPic: "suede-loafers.png",
    pics: ["suede-loafers1.png", "suede-loafers2.png", "suede-loafers3.png"],
    tags: ["Loafers", "Casual", "Footwear", "Men's", "Comfort", "Office"],
    variants: [
      { size: "40", color: "Brown", quantity: 12 },
      { size: "41", color: "Brown", quantity: 15 },
      { size: "42", color: "Brown", quantity: 10 },
    ],
  },
  {
    name: "Trench Coat",
    description: "Classic trench coat for rainy and cool days.",
    price: 150.0,
    season: "Autumn",
    mainPic: "trench-coat.png",
    pics: ["trench-coat1.png", "trench-coat2.png", "trench-coat3.png"],
    tags: ["Coat", "Outerwear", "Trench", "Women's", "Classic", "Rainwear"],
    variants: [
      { size: "S", color: "Beige", quantity: 10 },
      { size: "M", color: "Beige", quantity: 12 },
      { size: "L", color: "Beige", quantity: 8 },
    ],
  },
  {
    name: "White Sneakers",
    description: "Versatile white sneakers for casual and sports looks.",
    price: 65.0,
    season: "Spring",
    mainPic: "white-sneakers.png",
    pics: ["white-sneakers1.png", "white-sneakers2.png", "white-sneakers3.png"],
    tags: ["Sneakers", "Casual", "Footwear", "Unisex", "Classic", "Streetwear"],
    variants: [
      { size: "40", color: "White", quantity: 15 },
      { size: "41", color: "White", quantity: 18 },
      { size: "42", color: "White", quantity: 12 },
    ],
  },
  {
    name: "Wool Scarf",
    description: "Warm wool scarf for winter wear.",
    price: 35.0,
    season: "Winter",
    mainPic: "wool-scarf.png",
    pics: ["wool-scarf1.png", "wool-scarf2.png", "wool-scarf3.png"],
    tags: ["Scarf", "Winter", "Accessory", "Warm", "Unisex", "Knit"],
    variants: [{ size: "One Size", color: "Grey", quantity: 20 }],
  },
  {
    name: "Black Leather Jacket",
    description: "Stylish black leather jacket for casual and night outs.",
    price: 200.0,
    season: "Winter",
    mainPic: "black-leather-jacket.png",
    pics: [
      "black-leather-jacket1.png",
      "black-leather-jacket2.png",
      "black-leather-jacket3.png",
    ],
    tags: ["Jacket", "Leather", "Outerwear", "Men's", "Biker", "Edgy"],
    variants: [
      { size: "S", color: "Black", quantity: 8 },
      { size: "M", color: "Black", quantity: 10 },
      { size: "L", color: "Black", quantity: 6 },
    ],
  },
  {
    name: "Denim Jeans",
    description: "Classic blue denim jeans for everyday wear.",
    price: 55.0,
    season: "Spring",
    mainPic: "denim-jeans.png",
    pics: ["denim-jeans1.png", "denim-jeans2.png", "denim-jeans3.png"],
    tags: ["Jeans", "Casual", "Denim", "Men's", "Everyday", "Classic"],
    variants: [
      { size: "S", color: "Blue", quantity: 12 },
      { size: "M", color: "Blue", quantity: 15 },
      { size: "L", color: "Blue", quantity: 10 },
    ],
  },
  {
    name: "Floral Summer Dress",
    description: "Light floral dress for summer outings.",
    price: 60.0,
    season: "Summer",
    mainPic: "floral-summer-dress.png",
    pics: [
      "floral-summer-dress1.png",
      "floral-summer-dress2.png",
      "floral-summer-dress3.png",
    ],
    tags: ["Dress", "Summer", "Floral", "Women's", "Lightweight", "Casual"],
    variants: [
      { size: "S", color: "Floral", quantity: 10 },
      { size: "M", color: "Floral", quantity: 12 },
      { size: "L", color: "Floral", quantity: 8 },
    ],
  },
  {
    name: "Casual Hoodie",
    description: "Comfortable hoodie for daily wear.",
    price: 45.0,
    season: "Winter",
    mainPic: "casual-hoodie.png",
    pics: ["casual-hoodie1.png", "casual-hoodie2.png", "casual-hoodie3.png"],
    tags: ["Hoodie", "Casual", "Comfort", "Sportswear", "Unisex", "Fleece"],
    variants: [
      { size: "S", color: "Grey", quantity: 12 },
      { size: "M", color: "Grey", quantity: 14 },
      { size: "L", color: "Grey", quantity: 10 },
    ],
  },
  ////////here3
  {
    name: "Summer Sandals",
    description: "Light sandals for hot summer days.",
    price: 30.0,
    season: "Summer",
    mainPic: "summer-sandals.png",
    pics: ["summer-sandals1.png", "summer-sandals2.png", "summer-sandals3.png"],
    tags: [
      "Sandals",
      "Summer",
      "Footwear",
      "Casual",
      "Lightweight",
      "Open-toe",
    ],
    variants: [
      { size: "36", color: "Brown", quantity: 10 },
      { size: "37", color: "Brown", quantity: 12 },
      { size: "38", color: "Brown", quantity: 8 },
    ],
  },
  {
    name: "Patterned Shirt",
    description: "Shirt with unique patterns for casual style.",
    price: 50.0,
    season: "Spring",
    mainPic: "patterned-shirt.png",
    pics: [
      "patterned-shirt1.png",
      "patterned-shirt2.png",
      "patterned-shirt3.png",
    ],
    tags: ["Shirt", "Casual", "Patterned", "Men's", "Button-up", "Stylish"],
    variants: [
      { size: "S", color: "Mixed", quantity: 12 },
      { size: "M", color: "Mixed", quantity: 15 },
      { size: "L", color: "Mixed", quantity: 10 },
    ],
  },
  {
    name: "Winter Coat",
    description: "Heavy coat to stay warm during cold winter days.",
    price: 180.0,
    season: "Winter",
    mainPic: "winter-coat.png",
    pics: ["winter-coat1.png", "winter-coat2.png", "winter-coat3.png"],
    tags: ["Coat", "Winter", "Outerwear", "Warm", "Padded", "Unisex"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Classic Tee",
    description: "Simple and classic t-shirt for everyday wear.",
    price: 25.0,
    season: "Summer",
    mainPic: "classic-tee.png",
    pics: ["classic-tee1.png", "classic-tee2.png", "classic-tee3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "White", quantity: 20 },
      { size: "M", color: "White", quantity: 25 },
      { size: "L", color: "White", quantity: 18 },
    ],
  },
  {
    name: "Sun Dress",
    description: "Bright sundress perfect for sunny days.",
    price: 55.0,
    season: "Summer",
    mainPic: "sun-dress.png",
    pics: ["sun-dress1.png", "sun-dress2.png", "sun-dress3.png"],
    tags: ["Dress", "Summer", "Sundress", "Women's", "Casual", "Lightweight"],
    variants: [
      { size: "S", color: "Yellow", quantity: 12 },
      { size: "M", color: "Yellow", quantity: 14 },
      { size: "L", color: "Yellow", quantity: 10 },
    ],
  },
  {
    name: "Sweater Lethal",
    description: "Warm sweater with stylish design.",
    price: 60.0,
    season: "Winter",
    mainPic: "sweater-lethal.png",
    pics: ["sweater-lethal1.png", "sweater-lethal2.png", "sweater-lethal3.png"],
    tags: ["Sweater", "Casual", "Cozy", "Knitwear", "Unisex", "Warm"],
    variants: [
      { size: "S", color: "Grey", quantity: 10 },
      { size: "M", color: "Grey", quantity: 12 },
      { size: "L", color: "Grey", quantity: 8 },
    ],
  },
  {
    name: "Tees",
    description: "Casual tees for daily wear.",
    price: 20.0,
    season: "Summer",
    mainPic: "tees.png",
    pics: ["tees1.png", "tees2.png", "tees3.png"],
    tags: ["T-Shirt", "Casual", "Basic", "Unisex", "Everyday", "Cotton"],
    variants: [
      { size: "S", color: "Black", quantity: 20 },
      { size: "M", color: "Black", quantity: 25 },
      { size: "L", color: "Black", quantity: 18 },
    ],
  },
  {
    name: "Turtleneck Sweater",
    description: "Stylish turtleneck sweater for winter.",
    price: 65.0,
    season: "Winter",
    mainPic: "turtleneck-sweater.png",
    pics: [
      "turtleneck-sweater1.png",
      "turtleneck-sweater2.png",
      "turtleneck-sweater3.png",
    ],
    tags: ["Sweater", "Winter", "Turtleneck", "Knitwear", "Cozy", "Unisex"],
    variants: [
      { size: "S", color: "Black", quantity: 10 },
      { size: "M", color: "Black", quantity: 12 },
      { size: "L", color: "Black", quantity: 8 },
    ],
  },
  {
    name: "Unique Dress",
    description: "One-of-a-kind dress with unique patterns.",
    price: 80.0,
    season: "Autumn",
    mainPic: "unique-dress.png",
    pics: ["unique-dress1.png", "unique-dress2.png", "unique-dress3.png"],
    tags: ["Dress", "Elegant", "Unique", "Formal", "Women's", "Party"],
    variants: [
      { size: "S", color: "Red", quantity: 8 },
      { size: "M", color: "Red", quantity: 10 },
      { size: "L", color: "Red", quantity: 6 },
    ],
  },
  {
    name: "White Suit",
    description: "Elegant white suit for formal events.",
    price: 190.0,
    season: "Spring",
    mainPic: "white-suit.png",
    pics: ["white-suit1.png", "white-suit2.png", "white-suit3.png"],
    tags: ["Suit", "Formal", "Business", "Elegant", "Men's", "Wedding"],
    variants: [
      { size: "S", color: "White", quantity: 6 },
      { size: "M", color: "White", quantity: 8 },
      { size: "L", color: "White", quantity: 5 },
    ],
  },
  {
    name: "Winter Essentials",
    description: "Collection of essential items for winter.",
    price: 150.0,
    season: "Winter",
    mainPic: "winter-essentials.png",
    pics: [
      "winter-essentials1.png",
      "winter-essentials2.png",
      "winter-essentials3.png",
    ],
    tags: ["Winter", "Bundle", "Essentials", "Set", "Unisex", "Gift"],
    variants: [{ size: "One Size", color: "Mixed", quantity: 25 }],
  },
  {
    name: "YUS Formality Dress",
    description: "Formal dress for special occasions.",
    price: 120.0,
    season: "Autumn",
    mainPic: "yus-formality-dress.png",
    pics: [
      "yus-formality-dress1.png",
      "yus-formality-dress2.png",
      "yus-formality-dress3.png",
    ],
    tags: ["Dress", "Formal", "Elegant", "Women's", "Evening Wear", "Designer"],
    variants: [
      { size: "S", color: "Blue", quantity: 6 },
      { size: "M", color: "Blue", quantity: 8 },
      { size: "L", color: "Blue", quantity: 5 },
    ],
  },
];
