export const FakeProducts = [

  {
    name: "Jumpsuit",
    description: "Elegant one-piece outfit ideal for day-to-night occasions.",
    price: 99.99,
    season: "Spring",
    mainPic: "jumpsuit.png",
    pics: [],
    variants: [
      { size: "S", color: "Olive", quantity: 10 },
      { size: "M", color: "Olive", quantity: 9 },
      { size: "L", color: "Khaki", quantity: 6 },
    ],
    tags: ["Flowy", "Effortless", "Stylish"],
  },
  {
    name: "Knitted Full Dress",
    description: "Elegant knitted dress for cozy yet stylish looks.",
    price: 99.99,
    season: "Fall",
    mainPic: "knitted-full-dress.png",
    pics: [],
    variants: [
      { size: "S", color: "Beige", quantity: 8 },
      { size: "M", color: "Beige", quantity: 6 },
      { size: "L", color: "Cream", quantity: 5 },
    ],
    tags: ["Cozy", "Elegant", "Soft"],
  },
  {
    name: "Knitted Sweater",
    description: "Warm knitted sweater with a relaxed fit.",
    price: 59.5,
    season: "Winter",
    mainPic: "knitted-sweater.png",
    pics: [],
    variants: [
      { size: "S", color: "Gray", quantity: 12 },
      { size: "M", color: "Gray", quantity: 10 },
      { size: "L", color: "White", quantity: 8 },
    ],
    tags: ["Cozy", "Casual", "Warm"],
  },
  {
    name: "Lady Bug Dress",
    description: "Charming patterned dress with a playful vibe.",
    price: 79.99,
    season: "Spring",
    mainPic: "lady-bug-dress.png",
    pics: [],
    variants: [
      { size: "S", color: "Red", quantity: 9 },
      { size: "M", color: "Red", quantity: 8 },
      { size: "L", color: "Pink", quantity: 6 },
    ],
    tags: ["Playful", "Charming", "Spring"],
  },
  {
    name: "Leather Jacketr",
    description: "Classic leather jacket with sleek design.",
    price: 129.99,
    season: "Fall",
    mainPic: "leathe-jacketr.png",
    pics: [],
    variants: [
      { size: "S", color: "Black", quantity: 7 },
      { size: "M", color: "Black", quantity: 6 },
      { size: "L", color: "Brown", quantity: 5 },
    ],
    tags: ["Classic", "Edgy", "Layer"],
  },
  {
    name: "Leather Black Jacket",
    description: "Bold black leather jacket for statement outfits.",
    price: 139.99,
    season: "Fall",
    mainPic: "leather-black-jacket.png",
    pics: [],
    variants: [
      { size: "S", color: "Black", quantity: 6 },
      { size: "M", color: "Black", quantity: 5 },
      { size: "L", color: "Black", quantity: 4 },
    ],
    tags: ["Bold", "Edgy", "Statement"],
  },
  {
    name: "Leather Coat",
    description: "Stylish leather coat to keep you warm and chic.",
    price: 149.99,
    season: "Winter",
    mainPic: "leather-coat.png",
    pics: [],
    variants: [
      { size: "S", color: "Brown", quantity: 7 },
      { size: "M", color: "Brown", quantity: 6 },
      { size: "L", color: "Tan", quantity: 5 },
    ],
    tags: ["Chic", "Warm", "Stylish"],
  },
  {
    name: "Leather Oversize Jacket",
    description: "Oversized leather jacket for a modern casual look.",
    price: 159.99,
    season: "Winter",
    mainPic: "leather-oversize-jacket.png",
    pics: [],
    variants: [
      { size: "S", color: "Black", quantity: 5 },
      { size: "M", color: "Black", quantity: 4 },
      { size: "L", color: "Dark Brown", quantity: 3 },
    ],
    tags: ["Oversized", "Modern", "Casual"],
  },
  {
    name: "Max Harlynking Dress",
    description: "Soft dress perfect for everyday elegance.",
    price: 85.5,
    season: "Spring",
    mainPic: "max-harlynking-xwjwqNQRfAk-unsplash.png",
    pics: [],
    variants: [
      { size: "S", color: "Blue", quantity: 10 },
      { size: "M", color: "Blue", quantity: 9 },
      { size: "L", color: "Navy", quantity: 7 },
    ],
    tags: ["Soft", "Elegant", "Everyday"],
  },
  {
    name: "MDevil Dress",
    description: "Stylish patterned dress for casual and semi-formal outings.",
    price: 79.99,
    season: "Summer",
    mainPic: "mdevil-dress.png",
    pics: [],
    variants: [
      { size: "S", color: "Red", quantity: 8 },
      { size: "M", color: "Red", quantity: 7 },
      { size: "L", color: "Pink", quantity: 5 },
    ],
    tags: ["Patterned", "Casual", "Stylish"],
  },
  {
    name: "NewTown Cloth",
    description: "Trendy piece for unique and effortless looks.",
    price: 69.99,
    season: "Spring",
    mainPic: "newTown-cloth.png",
    pics: [],
    variants: [
      { size: "S", color: "Cream", quantity: 10 },
      { size: "M", color: "Cream", quantity: 9 },
      { size: "L", color: "Beige", quantity: 6 },
    ],
    tags: ["Trendy", "Effortless", "Unique"],
  },
  {
    name: "NewTown Easyday Suit",
    description: "Lightweight and stylish easyday suit for casual wear.",
    price: 129.99,
    season: "Summer",
    mainPic: "newTown-easyday-suit.png",
    pics: [],
    variants: [],
    tags: ["Casual", "Relaxed", "Chic", "Soft"],
  },
  {
    name: "NewTown Edition2 Suit",
    description: "Modern edition suit with soft tailoring and comfort.",
    price: 149.99,
    season: "Autumn",
    mainPic: "newTown-edition2-suit.png",
    pics: [],
    variants: [],
    tags: ["Elegant", "Contemporary", "Minimalist", "Polished"],
  },
  {
    name: "NewTown Fluf Jacket",
    description: "Cozy fluf jacket for cooler days.",
    price: 119.99,
    season: "Winter",
    mainPic: "newTown-fluf-jacket.png",
    pics: [],
    variants: [],
    tags: ["Cozy", "Warm", "Soft", "Layer"],
  },
  {
    name: "NewTown Formality Coat",
    description: "Tailored coat with clean lines for formal occasions.",
    price: 179.99,
    season: "Winter",
    mainPic: "newTown-formality-coat.png",
    pics: [],
    variants: [],
    tags: ["Refined", "Classic", "Polished", "Structured"],
  },
  {
    name: "NewTown Formality Dress",
    description: "Elegant dress designed for special occasions.",
    price: 139.99,
    season: "Spring",
    mainPic: "newTown-formality-dress.png",
    pics: [],
    variants: [],
    tags: ["Chic", "Graceful", "Sophisticated", "Light"],
  },
  {
    name: "NewTown Formality Jacket",
    description: "Formal jacket with structured style.",
    price: 159.99,
    season: "Autumn",
    mainPic: "newTown-formality-jacket.png",
    pics: [],
    variants: [],
    tags: ["Polished", "Tailored", "Classic", "Minimal"],
  },
  {
    name: "NewTown Formality Leathers",
    description: "Soft leather piece for refined looks.",
    price: 199.99,
    season: "Autumn",
    mainPic: "newTown-formality-leathers.png",
    pics: [],
    variants: [],
    tags: ["Lux", "Smooth", "Edgy", "Unique"],
  },
  {
    name: "NewTown Formality Patterned Shirt",
    description: "Shirt with subtle patterns for formal style.",
    price: 89.99,
    season: "Spring",
    mainPic: "newTown-formality-patterned-shirt.png",
    pics: [],
    variants: [],
    tags: ["Patterned", "Smart", "Clean", "Soft"],
  },
  {
    name: "NewTown Formality Sweater",
    description: "Warm and soft sweater for cooler days.",
    price: 99.99,
    season: "Winter",
    mainPic: "newTown-formality-sweater.png",
    pics: [],
    variants: [],
    tags: ["Cozy", "Layer", "Soft", "Minimal"],
  },
  {
    name: "NewTown Formality Wool Shirt",
    description: "Classic wool shirt with smooth texture.",
    price: 109.99,
    season: "Winter",
    mainPic: "newTown-formality-wool-shirt.png",
    pics: [],
    variants: [],
    tags: ["Warm", "Classic", "Clean", "Soft"],
  },
  {
    name: "NewTown Full Suit",
    description: "Full suit for modern elegant looks.",
    price: 189.99,
    season: "Autumn",
    mainPic: "newTown-full-suit.png",
    pics: [],
    variants: [],
    tags: ["Complete", "Tailored", "Polished", "Minimal"],
  },
  {
    name: "NewTown Leather Jacket",
    description: "Premium leather jacket with a refined finish.",
    price: 219.99,
    season: "Autumn",
    mainPic: "newTown-leather-jacket.png",
    pics: [],
    variants: [],
    tags: ["Edgy", "Smooth", "Statement", "Unique"],
  },
  {
    name: "Night Dress",
    description: "Elegant night dress for special occasions.",
    price: 129.99,
    season: "Spring",
    mainPic: "night-dress.png",
    pics: [],
    variants: [],
    tags: ["Flowy", "Chic", "Soft", "Graceful"],
  },
  {
    name: "Nord Citywear Coat",
    description: "Modern city coat with a lightweight feel.",
    price: 149.99,
    season: "Autumn",
    mainPic: "nord-citywear-coat.png",
    pics: [],
    variants: [],
    tags: ["Minimal", "Sleek", "Urban", "Light"],
  },
  {
    name: "Nord Citywear Multi",
    description: "Multi-purpose citywear piece with urban style.",
    price: 139.99,
    season: "Spring",
    mainPic: "nord-citywear-multi.png",
    pics: [],
    variants: [],
    tags: ["Functional", "Soft", "Simple", "Layer"],
  },
  {
    name: "Nord Citywear",
    description: "Classic citywear top for everyday use.",
    price: 109.99,
    season: "Summer",
    mainPic: "nord-citywear.png",
    pics: [],
    variants: [],
    tags: ["Urban", "Relaxed", "Clean", "Chic"],
  },
  {
    name: "Nord Dress",
    description: "Flowy nordic-inspired dress.",
    price: 119.99,
    season: "Spring",
    mainPic: "nord-dress.png",
    pics: [],
    variants: [],
    tags: ["Flowy", "Elegant", "Soft", "Light"],
  },
  {
    name: "Nord Easywear Dress",
    description: "Comfortable dress for easy wear.",
    price: 99.99,
    season: "Summer",
    mainPic: "nord-easywear-dress.png",
    pics: [],
    variants: [],
    tags: ["Casual", "Simple", "Soft", "Flowy"],
  },
  {
    name: "Nord Easywear Jacket",
    description: "Light jacket for everyday wear.",
    price: 129.99,
    season: "Spring",
    mainPic: "nord-easywear-jacket.png",
    pics: [],
    variants: [],
    tags: ["Light", "Urban", "Soft", "Minimal"],
  },
  {
    name: "Nord Easywear Pant",
    description: "Comfortable pant for casual styling.",
    price: 89.99,
    season: "Summer",
    mainPic: "nord-easywear-pant.png",
    pics: [],
    variants: [],
    tags: ["Relaxed", "Simple", "Soft", "Layer"],
  },
  {
    name: "Nord Easywear Shirt",
    description: "Soft and simple easywear shirt.",
    price: 79.99,
    season: "Summer",
    mainPic: "nord-easywear-shirt.png",
    pics: [],
    variants: [],
    tags: ["Simple", "Light", "Flowy", "Soft"],
  },
  {
    name: "Nord Easywear Sweater",
    description: "Soft sweater for layering.",
    price: 99.99,
    season: "Winter",
    mainPic: "nord-easywear-sweater.png",
    pics: [],
    variants: [],
    tags: ["Cozy", "Layer", "Soft", "Minimal"],
  },
  {
    name: "Nord Easywear Sweatshirt",
    description: "Casual sweatshirt for comfort.",
    price: 89.99,
    season: "Winter",
    mainPic: "nord-easywear-sweatshirt.png",
    pics: [],
    variants: [],
    tags: ["Soft", "Cozy", "Simple", "Light"],
  },
  {
    name: "Nord Formals Dress",
    description: "Formal dress for elegant occasions.",
    price: 149.99,
    season: "Spring",
    mainPic: "nord-formals-dress.png",
    pics: [],
    variants: [],
    tags: ["Elegant", "Chic", "Light", "Flowy"],
  },
  {
    name: "Nord Formals Jacket",
    description: "Polished jacket for formal styling.",
    price: 159.99,
    season: "Autumn",
    mainPic: "nord-formals-jacket.png",
    pics: [],
    variants: [],
    tags: ["Tailored", "Minimal", "Refined", "Polished"],
  },
  {
    name: "Nord Jeans",
    description: "Classic nord jeans for everyday use.",
    price: 99.99,
    season: "Summer",
    mainPic: "nord-jeans.png",
    pics: [],
    variants: [],
    tags: ["Casual", "Comfort", "Simple", "Urban"],
  },
  {
    name: "OldTown Suit",
    description: "Classic suit with elegant lines for versatile occasions.",
    price: 149.99,
    season: "Autumn",
    mainPic: "oldtown-su.png",
    pics: [],
    variants: [],
    tags: ["Refined", "Soft", "Minimal", "Chic"],
  },
  {
    name: "Olive Jacket",
    description: "Casual olive jacket for everyday layering.",
    price: 119.99,
    season: "Spring",
    mainPic: "olive-jacket.png",
    pics: [],
    variants: [],
    tags: ["Layered", "Soft", "Simple", "Cozy"],
  },
  {
    name: "Oversize Hoodie",
    description: "Comfortable oversized hoodie for relaxed style.",
    price: 89.99,
    season: "Winter",
    mainPic: "oversize-hoodie.png",
    pics: [],
    variants: [],
    tags: ["Casual", "Cozy", "Soft", "Relaxed"],
  },
  {
    name: "Oversize Unique Hoodie",
    description: "Statement hoodie with oversized relaxed fit.",
    price: 99.99,
    season: "Winter",
    mainPic: "oversize-unique-hoodie.png",
    pics: [],
    variants: [],
    tags: ["Unique", "Bold", "Comfort", "Relaxed"],
  },
  {
    name: "Pant with Pattern",
    description: "Patterned pants for a chic casual look.",
    price: 79.99,
    season: "Summer",
    mainPic: "pant-with-pattern.png",
    pics: [],
    variants: [],
    tags: ["Patterned", "Soft", "Chic", "Light"],
  },
  {
    name: "Pattern Outwear",
    description: "Light outwear with subtle patterns for style.",
    price: 109.99,
    season: "Autumn",
    mainPic: "pattern-outwear.png",
    pics: [],
    variants: [],
    tags: ["Patterned", "Urban", "Minimal", "Soft"],
  },
  {
    name: "Pattern Suit Essential",
    description: "Essential suit with subtle patterns for refined looks.",
    price: 159.99,
    season: "Spring",
    mainPic: "pattern-suit-essential.png",
    pics: [],
    variants: [],
    tags: ["Classic", "Patterned", "Minimal", "Elegant"],
  },
  {
    name: "Quality Sweater",
    description: "Premium sweater with soft texture for warmth.",
    price: 99.99,
    season: "Winter",
    mainPic: "quality-sweater.png",
    pics: [],
    variants: [],
    tags: ["Cozy", "Soft", "Minimal", "Layer"],
  },
  {
    name: "Revision Shirt",
    description: "Simple shirt with clean lines and soft fabric.",
    price: 79.99,
    season: "Summer",
    mainPic: "revesion-shirts.png",
    pics: [],
    variants: [],
    tags: ["Clean", "Soft", "Light", "Minimal"],
  },
  {
    name: "Revision Jacket",
    description: "Classic jacket with comfortable fit for daily wear.",
    price: 119.99,
    season: "Autumn",
    mainPic: "revision-jacket.png",
    pics: [],
    variants: [],
    tags: ["Layer", "Soft", "Chic", "Simple"],
  },
  {
    name: "Shiny Buff Jacket",
    description: "Jacket with subtle shine for modern looks.",
    price: 129.99,
    season: "Winter",
    mainPic: "shiny-buff-jacket.png",
    pics: [],
    variants: [],
    tags: ["Shiny", "Modern", "Minimal", "Soft"],
  },
  {
    name: "Shirt Cotton",
    description: "Soft cotton shirt for easy daily wear.",
    price: 69.99,
    season: "Summer",
    mainPic: "shirt-cotton.png",
    pics: [],
    variants: [],
    tags: ["Light", "Simple", "Soft", "Casual"],
  },
  {
    name: "Sindre Dress",
    description: "Stylish sundress with light and airy fabric.",
    price: 99.99,
    season: "Spring",
    mainPic: "sindre-aalberg-AdaFYMZW-nQ-unsplash.png",
    pics: [],
    variants: [],
    tags: ["Flowy", "Soft", "Chic", "Light"],
  },
  {
    name: "Soft Outwear",
    description: "Comfortable soft outwear for casual layering.",
    price: 109.99,
    season: "Autumn",
    mainPic: "soft-outwear.png",
    pics: [],
    variants: [],
    tags: ["Soft", "Light", "Relaxed", "Layer"],
  },
  {
    name: "Sport Pants",
    description: "Flexible pants designed for active wear.",
    price: 79.99,
    season: "Summer",
    mainPic: "sport-pants.png",
    pics: [],
    variants: [],
    tags: ["Active", "Soft", "Light", "Comfort"],
  },
  {
    name: "Sun Dress",
    description: "Bright and breezy sun dress for warm days.",
    price: 89.99,
    season: "Summer",
    mainPic: "sun-dress.png",
    pics: [],
    variants: [],
    tags: ["Flowy", "Soft", "Light", "Chic"],
  },
  {
    name: "Sweater Lethal",
    description: "Bold and stylish sweater with a unique texture.",
    price: 109.99,
    season: "Winter",
    mainPic: "sweater-lethal.png",
    pics: [],
    variants: [],
    tags: ["Soft", "Bold", "Cozy", "Layer"],
  },
  {
    name: "Tees",
    description: "Casual tees for relaxed everyday wear.",
    price: 49.99,
    season: "Summer",
    mainPic: "tees.png",
    pics: [],
    variants: [],
    tags: ["Soft", "Light", "Simple", "Casual"],
  },
  {
    name: "Tees2",
    description: "Lightweight casual tee for daily outfits.",
    price: 49.99,
    season: "Summer",
    mainPic: "tees2.png",
    pics: [],
    variants: [],
    tags: ["Soft", "Light", "Simple", "Casual"],
  },
  {
    name: "YUS Formality Dress",
    description: "Elegant dress designed for formal occasions.",
    price: 129.99,
    season: "Spring",
    mainPic: "YUS-formality-dress.png",
    pics: [],
    variants: [],
    tags: ["Flowy", "Elegant", "Chic", "Light"],
  },
];
